### ISSUE TITLE
helpメッセージに DISCORD_CMD_PREFIX の設定を反映させる

### ISSUE THREAD

**Issue by zinntikumugai** [tktcorporation/discord-speech-bot#18]
<img width="358" alt="スクリーンショット 2021-08-05 21 25 24" src="https://user-images.githubusercontent.com/16275962/128349475-66039b8d-6584-4f9e-beb0-cd0f2667236e.png">

**Comment by tktcorporation** [comment]
![image](https://user-images.githubusercontent.com/37575408/129147397-b1f8ac7a-2a55-434a-b184-aa0c7552ad60.png)
特に問題ないような

**Comment by tktcorporation** [comment]
あ、理解
`DISCORD_CMD_PREFIX` を `,` にしたときには
「`,join` でボイスチャットに入るよ」って出るべきってことか
