### ISSUE TITLE
ウェルカムメッセージをサーバー内の名前を呼ぶように

### ISSUE THREAD

**Issue by zinntikumugai** [tktcorporation/discord-speech-bot#22]
サーバー内の名前と実際の名前が異なる場合があるため、読み上げる名前をサーバー内の名前にしたほうが良さげ  

ex
名前: `zinntikumugai`
サーバー内の名前: `zin3`

[該当箇所](https://github.com/tktcorporation/discord-speech-bot/blob/fcda9eaa41e37fb665da5b4a7b9099c29e694524/src/handler/mod.rs#L72)

**Comment by tktcorporation** [comment]
サーバー内の名前の取り方調査
